name: Build ZIP

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'build/**'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create build folder
        run: mkdir -p build

      - name: Create ZIP
        run: |
          zip -r build/site.zip . \
          -x ".git/*" \
          -x "build/*"

      - name: Commit ZIP
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add build/site.zip
          git commit -m "auto update zip" || echo "no changes"
          git push